"""
CRITIQUE — NLP Generation Metrics (ROUGE-L, ROUGE-1, ROUGE-2, BLEU)
===================================================================

Computes standard NLP code review generation metrics comparing
fine-tuned Critique LLM outputs against human expert reference reviews:
  - ROUGE-L (Longest Common Subsequence)
  - ROUGE-1 (Unigram overlap)
  - ROUGE-2 (Bigram overlap)
  - BLEU-4 Score
"""

import sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import json
from rouge_score import rouge_scorer
import nltk
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

# Reference ground-truth expert reviews for our benchmark cases
GROUND_TRUTH_REVIEWS = {
    "SEC-01": (
        "SQL injection vulnerability detected. The query concatenates user input directly into the SQL string. "
        "Use parameterized queries with placeholders like `cursor.execute('SELECT * FROM accounts WHERE username = %s', (user_input,))`."
    ),
    "BUG-01": (
        "Mutable default parameter `enrolled_courses=[]`. Default parameter values are evaluated once when the function is defined. "
        "Mutations will persist across subsequent calls. Use `enrolled_courses=None` as default and initialize inside body."
    ),
    "RES-01": (
        "Unclosed resource leak. The file is opened with `open()` but never closed, risking descriptor leaks if an error occurs. "
        "Always use a `with open(...)` context manager."
    ),
    "SEC-02": (
        "Hardcoded API secret token found in source code. Storing credentials directly in code risks unauthorized exposure. "
        "Load API keys from environment variables using `os.getenv('API_KEY')`."
    ),
    "BUG-02": (
        "Bare `except:` clause catches all exceptions and silently swallows errors with `pass`. "
        "Catch specific exception classes like `except DatabaseError:` and log the error properly."
    ),
    "LOG-01": (
        "Off-by-one logic error in pagination. 1-indexed pagination requires `start = (page_number - 1) * page_size`. "
        "Current implementation skips the first page entirely."
    ),
}

def main():
    print("=" * 75)
    print("      CRITIQUE — NLP GENERATION METRICS (ROUGE-L, ROUGE-1, BLEU)")
    print("=" * 75)

    # Load the actual predictions generated by our model from benchmark_scores.json
    with open("benchmark_scores.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
    smoothie = SmoothingFunction().method1

    rouge1_f1s = []
    rouge2_f1s = []
    rougeL_f1s = []
    bleu_scores = []

    print(f"\n{'ID':<10} | {'Test Case':<32} | {'ROUGE-1':<9} | {'ROUGE-2':<9} | {'ROUGE-L':<9} | {'BLEU':<6}")
    print("-" * 75)

    for case in data["cases"]:
        case_id = case["id"]
        if case_id not in GROUND_TRUTH_REVIEWS:
            continue  # Clean cases don't have bug review references

        ref = GROUND_TRUTH_REVIEWS[case_id]
        cand = case.get("review", "")

        # Compute ROUGE
        scores = scorer.score(ref, cand)
        r1 = scores['rouge1'].fmeasure
        r2 = scores['rouge2'].fmeasure
        rL = scores['rougeL'].fmeasure

        # Compute BLEU
        import re
        ref_tokens = [re.findall(r"\w+", ref.lower())]
        cand_tokens = re.findall(r"\w+", cand.lower())
        bleu = sentence_bleu(ref_tokens, cand_tokens, smoothing_function=smoothie)

        rouge1_f1s.append(r1)
        rouge2_f1s.append(r2)
        rougeL_f1s.append(rL)
        bleu_scores.append(bleu)

        print(f"{case_id:<10} | {case['name'][:32]:<32} | {r1*100:6.1f}%  | {r2*100:6.1f}%  | {rL*100:6.1f}%  | {bleu*100:4.1f}%")

    avg_r1 = sum(rouge1_f1s) / len(rouge1_f1s) if rouge1_f1s else 0
    avg_r2 = sum(rouge2_f1s) / len(rouge2_f1s) if rouge2_f1s else 0
    avg_rL = sum(rougeL_f1s) / len(rougeL_f1s) if rougeL_f1s else 0
    avg_bleu = sum(bleu_scores) / len(bleu_scores) if bleu_scores else 0

    print("=" * 75)
    print("                     OVERALL NLP GENERATION REPORT")
    print("=" * 75)
    print(f"  • ROUGE-L Score (LCS F1) : {avg_rL * 100:.2f}%  (Longest Common Subsequence)")
    print(f"  • ROUGE-1 Score (Unigram): {avg_r1 * 100:.2f}%  (Vocabulary overlap)")
    print(f"  • ROUGE-2 Score (Bigram) : {avg_r2 * 100:.2f}%  (Phrase & syntax alignment)")
    print(f"  • BLEU-4 Score           : {avg_bleu * 100:.2f}%  (N-gram precision)")
    print("=" * 75)

    # Save to json
    with open("nlp_generation_metrics.json", "w", encoding="utf-8") as f:
        json.dump({
            "rougeL_f1": round(avg_rL * 100, 2),
            "rouge1_f1": round(avg_r1 * 100, 2),
            "rouge2_f1": round(avg_r2 * 100, 2),
            "bleu4": round(avg_bleu * 100, 2),
        }, f, indent=2)
    print("Saved to nlp_generation_metrics.json")

if __name__ == "__main__":
    main()
